[project]
name = "exploratory-data-analysis"
version = "0.1.0"
description = "Iris EDA"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
]
